[versions]
agp = "8.11.0"
kotlin = "2.2.0"

javaVersion = "21"
compileSdk = "36"
minSdk = "21"
targetSdk = "33"

[libraries]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
