[package]
author = "Hans Ellegård <psyill.net@gmail.com>"
edition = "2024"
name = "adorno-filter"
publish = false
version = "0.1.0"

[dependencies]
console = "0.15.11"

[profile.release]
lto = true
opt-level = "z"
